server:
  # Vue app will run on port 8080
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
okta:
  oauth2:
    issuer: https://dev-54064931.okta.com/oauth2/default
spring:
  application:
    name: ApiGateway
  main:
    allow-bean-definition-overriding: true
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
      httpclient:
        ssl:
          useInsecureTrustManager: true
    routes:
    - id: users
      uri: lb://PHOTOAPPAPI-USERS
      predicates:
        - Path=/users/**
    - id: albums
      uri: lb://PHOTOAPPAPI-ALBUMS
      predicates:
        - Path=/albums/**
    - id: dotnet
      uri: lb://TransactionHistoryService
      predicates:
          - Path=/weatherforecast/**