server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
spring:
  application:
    name: ApiGateway
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
      - id: users
        uri: lb://PHOTOAPPAPI-USERS
        predicates:
          - Path=/users/**